name: Publish NuGet Package

on:
  pull_request:
    branches:
      - master

jobs:
  publish:
    name: Publish to NuGet
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up .NET Core
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Cambia según tu framework

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build the project
      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      # 5. Pack the project
      - name: Pack the project
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      # 6. Publish to NuGet
      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_SECRET }} --source https://api.nuget.org/v3/index.json